language: php
php:
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - php: 7.0
before_install:
  - curl -s https://get.webino.org/support/travis/before-install | sudo -E sh
install:
  - curl -s https://get.webino.org/support/travis/install | sh
before_script:
  - curl -s https://get.webino.org/support/travis/before-script | sh
script:
  - curl -s https://get.webino.org/support/travis/script | sh
  - cat /tmp/selenium/port-4444.log
after_success:
  - curl -s https://get.webino.org/support/travis/after-success | sh
env:
  global:
    - URI=http://localhost:8000/
    - BROWSER=firefox
    - GH_REF=github.com/webino/WebinoDev
    - secure: Q/YU5hwfkcGFKniOEAuXbEf/MXi5+l8LtIw5XYg963DLLhqCqZ55GshsZp1btL32ftM6K5qkZuxMLQQAlPA8LCKzte9KN8z/NIWsBlOJl6uv1fPBKD2BILlPBw11VYEaPexDMvOL1HRP3kxYNUmQ179Fg2WmnMjpB3OpuNkoBTE=
