<?php
/**
 * Webino (http://webino.sk/)
 *
 * @link        https://github.com/webino/WebinoDev/ for the canonical source repository
 * @copyright   Copyright (c) 2014-2016 Webino, s. r. o. (http://webino.sk/)
 * @license     BSD-3-Clause
 */

namespace WebinoDev\Test\Selenium\WebDriver;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-10-27 at 17:17:42.
 */
class TestElementTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TestElement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestElement;
    }

    /**
     * @covers WebinoDev\Test\Selenium\WebDriver\TestElement::text
     */
    public function testText()
    {
        $this->object->text();
    }

    /**
     * @covers WebinoDev\Test\Selenium\WebDriver\TestElement::attribute
     */
    public function testAttribute()
    {
        $this->object->attribute('test');
    }

    /**
     * @covers WebinoDev\Test\Selenium\WebDriver\TestElement::click
     */
    public function testClick()
    {
        $this->object->click();
    }

    /**
     * @covers WebinoDev\Test\Selenium\WebDriver\TestElement::clear
     */
    public function testClear()
    {
        $this->object->clear();
    }

    /**
     * @covers WebinoDev\Test\Selenium\WebDriver\TestElement::sendKeys
     */
    public function testSendKeys()
    {
        $this->object->sendKeys('');
    }

    /**
     * @covers WebinoDev\Test\Selenium\WebDriver\TestElement::submit
     */
    public function testSubmit()
    {
        $this->object->submit();
    }
}
