<?php
/**
 * Webino (http://webino.sk/)
 *
 * @link        https://github.com/webino/WebinoDev/ for the canonical source repository
 * @copyright   Copyright (c) 2014 Webino, s. r. o. (http://webino.sk/)
 * @license     BSD-3-Clause
 */

namespace WebinoDev\Test\Selenium\WebDriver;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-10-27 at 17:20:44.
 */
class TestWebDriverTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TestWebDriver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestWebDriver;
    }

    /**
     * @covers WebinoDev\Test\Selenium\WebDriver\TestWebDriver::session
     */
    public function testSession()
    {
        $session = $this->object->session();
        $this->assertInstanceOf('WebinoDev\Test\Selenium\WebDriver\TestSession', $session);
    }
}
